name: Auto Checkin Job

on:
  schedule:
    # 每天早上 5 点半北京时间（UTC+8）运行
    - cron: '30 21 * * *'  # UTC 时间 21:30 对应北京时间 5:30
  workflow_dispatch:  # 允许手动触发

jobs:
  auto-sign:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果有依赖文件

      # 4. 运行脚本并捕获输出
      - name: Run auto checkin script
        id: run_script  # 给步骤命名，方便后续引用输出
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BARK_DEVICE_KEY: ${{ secrets.BARK_DEVICE_KEY }}
          BARK_SERVER_URL: ${{ secrets.BARK_SERVER_URL }}
          WECHAT_WORK_CORPID: ${{ secrets.WECHAT_WORK_CORPID }}
          WECHAT_WORK_AGENTID: ${{ secrets.WECHAT_WORK_AGENTID }}
          WECHAT_WORK_SECRET: ${{ secrets.WECHAT_WORK_SK }}
          WECHAT_WORK_USERID: ${{ secrets.WECHAT_WORK_USERID }}
        run: |
          python auto_checkin.py
